/*   This program is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef _SYSCALL
#define _SYSCALL

#include "Idt.h"

#define INFO_PROCESSOS 	1
#define INFO_MENSAGENS 	2
#define INFO_MEMORIA 	3
#define INFO_VFS 	4


/**
*Informações sobre as system calls no sistema feSO
 
|    Nome                  |    Descrição                                                                                                                                                                                                                                                                                                                                                  |    Parâmetros                                                                                                                                                                                                                                                                                                                                               |    Retorno                                                                 |    Principais métodos chamados                                                                                                                                                |
|--------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|    sbk                   |    Aumenta   o heap do processo.                                                                                                                                                                                                                                                                                                                              |    -EAX   = 0   -EBX   = Quantidade de memória                                                                                                                                                                                                                                                                                                              |    -EAX   = Endereço do início do novo bloco alocado.                      |    escalonador.obter_thread   escalonador.obter_processo   processo.aumentar_heap                                                                                             |
|    obter_info_kernel     |    Armazena   informações sobre o funcionamento de alguns componentes do Kernel em   arquivos.                                                                                                                                                                                                                                                                |    -EAX   = 1   -EBX   = Ponteiro para cadeia de caracteres com o nome do arquivo   -ECX   = código para definir sobre qual área do Kernel obter informações                                                                                                                                                                                                |                                                                            |    escolandor.obter_info   entregador.obter_info   mem_fisica.obter_info                                                                                                      |
|    enviar_msg            |    Envia   uma mensagem de forma síncrona para uma determinada porta.                                                                                                                                                                                                                                                                                         |    -EAX   =2   -EBX=   Ponteiro para a mensagem.   -ECX   = porta   -EDX   =flag para sinalizar recebimento                                                                                                                                                                                                                                                 |    EAX   = retorno da função enviar_msg                                    |    entregador.tratar_envio   escalonador.adicionar_mensagem   escalonador.colocar_thread_atual_em_espera   escalonador.executar_prox_thread                                   |
|    enviar_msg_pid        |    Envia   uma mensagem de forma assíncrona para um determinado pid.                                                                                                                                                                                                                                                                                          |    -EAX   =3   -EBX=   Ponteiro para a mensagem.   -ECX   = pid de destino                                                                                                                                                                                                                                                                                  |    EAX   = retorno da função enviar_msg_pid                                |    entregador.tratar_envio_pid   escalonador.adicionar_mensagem                                                                                                               |
|    receber_msg           |    Verifica   se há mensagens para a thread vindos   de uma determinada porta. Caso haja, retorna o processo, senão, o coloca em   estado de espera.                                                                                                                                                                                                          |    -EAX   =4   -EBX=   Ponteiro para a mensagem.   -ECX   = porta                                                                                                                                                                                                                                                                                           |    EAX   = retorno da função receber_msg                                   |    entregador.tratar_recebimento   escalonador.obter_mensagem   escalonador.acordar_thread   escalonador.colocar_thread_atual_em_espera   escalonador.executar_prox_thread    |
|    escutar_porta         |    Aloca   uma porta para uma thread. De forma   que as mensagens enviadas para porta são encaminhadas à thread.                                                                                                                                                                                                                                              |    -EAX   =5   -EBX=   porta                                                                                                                                                                                                                                                                                                                                |    EAX   = retorno da função receber_msg                                   |    entregador.adicionar_listerner   entregador.notificar_evento                                                                                                               |
|    abrir_arquivo         |    Abre   um arquivo para edição, ou cria o arquivo caso ele não exista. Comportamento   condicionada por parâmetros.                                                                                                                                                                                                                                         |    -EAX   =6   -EBX=   caminho do arquivo   -ECX   = modo de abertura   -EDX   = ponteiro para onde ficará armazenado o pid do servidor                                                                                                                                                                                                                     |    -EAX   = retorno da função vfs.abrir   -EBX   = descritor do arquivo    |    vfs.abrir   entregador.notificar_evento                                                                                                                                    |
|    ler_arquivo           |    Realiza   a leitura do arquivo, e copia os dados lidos para uma posição de memória   especificada.                                                                                                                                                                                                                                                         |    -EAX   =7   -EBX=   descritor do arquivo   -ECX   = ponteiro para o buffer de memória   -EDX   = quantidade de bytes a serem lidos                                                                                                                                                                                                                       |    -EAX   = retorno da função vfs.ler                                      |    Vfs.ler   entregador.notificar_evento                                                                                                                                      |
|    escrever_arquivo      |    Realiza   a escrita do arquivo, armazenando os dados especificados dentro do arquivo.                                                                                                                                                                                                                                                                      |    -EAX   =8   -EBX=   descritor do arquivo   -ECX   = ponteiro para o buffer de memória   -EDX   = quantidade de bytes a serem escritos                                                                                                                                                                                                                    |    -EAX   = retorno da função vfs.escrever                                 |    vfs.escrever   entregador.notificar_evento                                                                                                                                 |
|    buscar_arquivo        |    Altera   o valor do variável indicador de posição dentro do arquivo. Depois dessa   chamada, todas as leituras e escritas de dados no arquivo são feitas a partir   da posição especificada.                                                                                                                                                               |    -EAX   =9   -EBX=   descritor do arquivo   -ECX   = nova posição                                                                                                                                                                                                                                                                                         |    -EAX   = retorno da função vfs.buscar                                   |    vfs.buscar                                                                                                                                                                 |
|    excluir_arquivo       |    Remove   um nó de arquivo do VFS.                                                                                                                                                                                                                                                                                                                          |    -EAX   = 10   -EBX   = descritor do arquivo.                                                                                                                                                                                                                                                                                                             |    -EAX   = retorno da função vfs.excluir                                  |    vfs.excluir   entregador.notificar_evento                                                                                                                                  |
|    fechar_arquivo        |    Altera   o estado do arquivo para fechado, não permitindo operações de escrita e   leitura. Coloca o indicador da posição em 0.                                                                                                                                                                                                                            |    -EAX   = 11   -EBX   = descritor do arquivo.                                                                                                                                                                                                                                                                                                             |    -EAX   = retorno da função vfs.fechar                                   |    vfs.fechar   entregador.notificar_evento                                                                                                                                   |
|    obter_info_arquivo    |    Retorna   informações sobre um nó do vfs.                                                                                                                                                                                                                                                                                                                  |    -EAX   = 15   -EBX   = descritor do arquivo.   -ECX   = ponteiro para posição de memória onde os dados devem ser armazenados                                                                                                                                                                                                                             |    -EAX   = retorno da função obter_info_arquivo                           |    Vfs.obter_info_arquivo                                                                                                                                                     |
|    adicionar_no          |    Adiciona   um nó de um sistema de arquivo externo no vfs.                                                                                                                                                                                                                                                                                                  |    -EAX   = 16   -EBX   = ponteiro para string com o caminho do novo nó   -ECX   = tamanho do arquivo no sistema de arquivos externo   -EDX   = ponteiro para inteiro onde será armazenado o novo descritor do arquivo.   -ESI   = número da porta para a qual devem ser encaminhadas as solicitações de   abertura, fechamento e exclusão dos arquivos.    |    -EAX   = retorno da função vfs.adicionar_no.                            |    vfs.adicionar_no   vfs.abrir                                                                                                                                               |
|    montar_no             |    Chamada   utilizada para que sistemas de arquivos externos possam controlar o acesso a arquivos.   Quando uma solicitação de abertura a um arquivo externo é feita, o servidor é   informado, e ele então carrega os dados do arquivo na memória, e usa essa   chamada para alterar o estado do arquivo permitindo o seu acesso por outros   processos.    |    -EAX   = 17   -EBX   = descritor do arquivo                                                                                                                                                                                                                                                                                                              |    -EAX   = retorno da função vfs.montar_no                                |    vfs.montar_no                                                                                                                                                              |
|    remover_no            |    Torna   um nó no vfs inacessível aos outros processos.                                                                                                                                                                                                                                                                                                     |    -EAX   = 19   -EBX   = descritor do arquivo                                                                                                                                                                                                                                                                                                              |    -EAX   = retorno da função remover_no                                   |    vfs.remover_no                                                                                                                                                             |
|    executar              |    Cria   e executa um novo processo a partir de um arquivo executável no formato ELF.                                                                                                                                                                                                                                                                        |    -EAX   = 12   -EBX   = nome do novo processo   -EDX   = ponteiro para string com parâmetros   -ESI   = descritor do arquivo executável                                                                                                                                                                                                                   |    -EAX   = retorno da função adicionar_processo                           |    vfs.obter_imagem   escalonador.adicionar_processo   processo.criar_processo   entregador.notificar_evento                                                                  |
|    sair                  |    Elimina   a thread que realizou a chamada.   Caso está seja a thread principal,   todo o processo é eliminado                                                                                                                                                                                                                                              |    -EAX   = 13                                                                                                                                                                                                                                                                                                                                              |                                                                            |    escalonador.obter_thread   escalonador.obter_processo   escalonador.eliminar_processo   escalonador.executar_prox_thread   entregador.notificar_evento                     |
|    obter_pid             |    Obtém   o pid da thread em execução, ou o   pid do processo de alguma outra thread.                                                                                                                                                                                                                                                                        |    -EAX   = 14   -EBX   = pid da thread para a qual se quer   saber o id do processo. Caso 0 retorna pid da thread em execução.                                                                                                                                                                                                                             |    -EAX   = pid solicitado                                                 |    escalonador.obter_pid_em_execucao   escalonador.obter_thread                                                                                                               |
|    finalizar_processo    |    Elimina   o processo especificado. Está chamado só pode ser realizado para um processo   pai tentando eliminar um processo filho.                                                                                                                                                                                                                          |    -EAX   = 19   -EBX   = pid do processo a ser a eliminado.                                                                                                                                                                                                                                                                                                |                                                                            |    escalonador.obter_pid_em_execucao   escalonador.eliminar_processo   entregador.notificar_evento                                                                            |
|    criar_thread          |    Cria   uma nova thread para processo que   comece a executar a partir de um ponto de entrada.                                                                                                                                                                                                                                                              |    -EAX   = 20   -EBX   = ponto de entrada da nova thread                                                                                                                                                                                                                                                                                                   |    EAX   = Retorno da função adicionar_thread.                             |    escalonador.obter_thread   escalonador.obter_processo   escalonador.adicionar_thread                 
*/
class Syscall
{
	
   public :
   
   unsigned int num;
   void inicializar(Idt idt);
   void chamar_systemcall(struct REGS *r);
   void sbrk(struct REGS *r);
   void obter_info_kernel(struct REGS *r);
   void enviar_msg(struct REGS *r);
   void enviar_msg_pid(struct REGS *r);
   void receber_msg(struct REGS *r);
   void escutar_porta(struct REGS *r);
   void abrir_arquivo(struct REGS *r);
   void ler_arquivo(struct REGS *r);
   void escrever_arquivo(struct REGS *r);
   void buscar_arquivo(struct REGS *r);
   void excluir_arquivo(struct REGS *r);
   void fechar_arquivo(struct REGS *r);
   void executar(struct REGS *r);
   void sair(struct REGS *r);
   void finalizar_proceso(struct REGS *r);
   void criar_thread(struct REGS *r);
   void obter_pid(struct REGS *r);
   void obter_info_arquivo(struct REGS *r);
   void adicionar_no(struct REGS *r);
   void montar_no(struct REGS *r);
   void remover_no(struct REGS *r);
};
 
extern Syscall syscall;

#endif
